jenkinsci/parameterized-remote-trigger-plugin

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java
Error message was not being displayed in console output or logs. A lot of errors fall under IOException, so it would be useful to at least display the error message for why it is unable to execute the build.
@reviewbybees
=> Add error message when connection fails

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java, src/main/resources/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration/config.jelly, src/main/resources/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration/help-enhancedLogging.html, src/test/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfigurationTest.java
This somewhat solves https://issues.jenkins-ci.org/browse/JENKINS-25265 and https://issues.jenkins-ci.org/browse/JENKINS-23748.
=> added debug to connection errors, added console output

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java
Setting read timeout in sendHTTPCall() to 5000 to avoid deadlock during response read.
=> [JENKINS-33269] Possible deadlock during checking remote job

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java
Checks the property job metadata field in addition to the actions array
Fixes #JENKINS-52673
=> Updated parameterized build detection

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java
When deserializing a job configuration from an older version,
the hostLocks and hostPermits fields will be null as they
were not present in the older versions.  This can cause a
NullPointerException when running a job with an older
configuration.
Fix this by ensuring older configurations get proper default
values for these fields, if missing.
=> [FIX JENKINS-52810] Ensure older configurations work when deserialized.

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java
Fix releated to the issue:
https://issues.jenkins-ci.org/browse/JENKINS-55038
There is a problem when we try to use poll interval parameter's value
more than 300 seconds(5 minutes). We have a Jenkins pipeline which may
take from 30 to 60 minutes.
In some cases Jenkins `queued` item may move to the `pending` state as
it described here:
https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Queue.java#L139
In such case the plugin use user specified poll interval time out value
to check `queued` item state:
https://github.com/jenkinsci/parameterized-remote-trigger-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java#L696
But all `queued` items in the Jenkins have time to live only 5 minutes
as you can see it …
=> Fix fails with poll interval value more than 5 min

README_PipelineConfiguration.md, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/pipeline/Handle.java
**changes:**
- correct method name as changed in https://github.com/jenkinsci/parameterized-remote-trigger-plugin/pull/38
- correct return type
=> correct method name in docs

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteJenkinsServer.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/pipeline/RemoteBuildPipelineStep.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/utils/HttpHelper.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/utils/NaiveTrustManager.java, src/main/resources/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration/config.jelly, src/main/resources/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration/help-trustAllCertificates.html, src/main/resources/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteJenkinsServer/config.jelly, src/main/resources/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteJenkinsServer/help-trustAllCertificates.html, src/main/resources/org/jenkinsci/plugins/ParameterizedRemoteTrigger/pipeline/RemoteBuildPipelineStep/config.jelly, src/main/resources/org/jenkinsci/plugins/ParameterizedRemoteTrigger/pipeline/RemoteBuildPipelineStep/help-trustAllCertificates.html, src/test/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfigurationTest.java
**Added**
- A "NaiveTrustManager", which allows to bypass certificate checks
-> Enables us to accept any certificate
- TrustAllCertificates option for Jenkins Admins (globally) and Jenkins users (per job/pipeline)
- Overwriting the 'global' TrustAllCertificates option per job and pipeline is possible
=> Added ability to accept untrusted certificates

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java, src/test/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfigurationTest.java
Currently the plugin fails to get the root URL of a remote job if it belongs in a view at the root level. This change should enable support for remote job in views. I've added a new test case for a job in a view. Let me know if any other testing is required?
=> Added support for views

pom.xml, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java
- Set min jenkins to 2.60.3 this is the first version of jenkins to require java 8
- Bump plugin pom
- Mark the map with semaphore values as transient so it does not get serialized
=> [JENKINS-56770] Do not serialize semaphores

README_PipelineConfiguration.md, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/auth2/BearerTokenAuth.java, src/test/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/auth2/Auth2Test.java
When Jenkins is running on top of OpenShift, bearer token authentication is used for all REST API calls.
This means the API requests are authenticated via a header like:
`Authorization: Bearer <Kubernetes/OpenShift Token>`
I've been using these modifications to the plugin to trigger remote jobs on a master deployed on OpenShift with the OpenShift authentication enabled.
Example usage in a pipeline:
```
def jobParameters = [[$class: StringParameterValue, name: "someParam", value: "someValue"]]
// Translate the params into a string
def paramsString = ""
for (Map p : jobParameters) {
paramsString = paramsString + "\n${p['name']}=${p['value'].toString()}"
}
withCredentials([
string(credentialsId: remoteCredentials, variable: "TOKEN"),
string(credentialsId: remoteHostname, variable: …
```
=> Add support for Bearer Token Authentication

README_PipelineConfiguration.md
Currently, if the example is used as is, the `buildStatus` doesn't really change which leads to endless polling
=> add handler.updateBuildStatus() to non-blocking example

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java, src/test/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfigurationTest.java
When the remoteJenkinsUrl specifies a different protocol or port than the Jenkins API reports, the build will fail because the Build URL is wrong. This is because only the hostname is replaced on the URL returned from the Jenkins API.
My Jenkins server is accessed from two networks, one of which has a reverse proxy with only SSL. When builds are triggered on the SSL side, the remote job will start but it cannot poll for the build status because the build URL is wrong (http instead of https).
I fixed the issue by copying the request path onto the remoteJenkinsURL
```
remoteJenkinsUrl: 'https://external-jenkins:8443'
Before change:
http://internal-jenkins/job/MyProject/3/ -> http://external-jenkins/job/MyProject/3/
After change:
http://internal-jenkins/job/MyProject/3/ -> …
```
=> Override remote build URL protocol and port

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/pipeline/Handle.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/pipeline/RemoteBuildPipelineStep.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/utils/RestUtils.java, src/test/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfigurationTest.java
The poll interval depends from context of remote build.
Regression fix for:
https://issues.jenkins-ci.org/browse/JENKINS-55038
All items in Jenkins queue cache have TTL 5 minutes
https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Queue.java#L217-L222
=> Set restriction on pollinterval for items in queue

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java
This commit sets up a CookieManager and makes the system-wide CookieHandler use it.
Starting from Jenkins LTS 2.176.2 a valid Web Session for which the crumb was issued is also required unless configured otherwise.
=> Setup CookieHandler

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/ConnectionResponse.java, src/test/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/remoteJob/QueueItemTest.java
For remote jekins that provides all lower-case HTTP headers, the parameterized remote trigger will fail with error such as
```
ERROR: Remote build failed with 'AbortException' for the following reason: 'Error triggering the remote job. The header of the response has an unexpected format: 
{date=[Tue, 21 Apr 2020 02:26:47 GMT], null=[HTTP/1.1 201 Created], server=[envoy], content-length=[0], x-envoy-upstream-service-time=[15], x-content-type-options=[nosniff], location=[http://example.com/jenkins/myjenkins/queue/item/4848912/]}'.
```
It seems the plugin is looking for "Location" but only "location" is provided.
=> http headers should be case insensitive

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/auth2/CredentialsAuth.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/auth2/TokenAuth.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/pipeline/Handle.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/utils/Base64Utils.java, src/test/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/utils/Base64UtilsTest.java
Signed-off-by: Raihaan Shouhell <raihaan.shouhell@autodesk.com>
CredentialsAuth uses the jenkins cred store for its credentials it should not require env var expansion. This allows passwords to contain the dollar sign
PTAL: @cashlalala
=> Only use token macro on user supplied values

pom.xml
Point the pom to github so plugin documentation on https://plugins.jenkins.io/Parameterized-Remote-Trigger/ is properly updated with the repositories contents
=> Point pom to github so plugin documentation is updated

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java
As the author of this PR https://github.com/jenkinsci/parameterized-remote-trigger-plugin/pull/55 doesn't answer to the proposed fix in his fork, here is the appropriate change fixing the infinite loop due to the "building" status which was not retrieved in the original PR.
Retrieving only requested fields meaning result & building which are used later in the code will greatly improve performances specially in large builds archiving lot of files or others contents in the returned build api/json payload  as all these others informations are not needed & will increase the json marshaling & transfer time sometimes to some MB & lot of minutes.  
As side effect, without that optimization if the get call spends more than the timeout duration due to the size of data , it will ends with some …
=> retrieve only needed "doGetting" build fields

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/utils/HttpHelper.java
First of all, only HTTP Error code was displayed on retries. In case of
no error code, the exception message is also displayed.
Also, on the final failure/last retry, an error message is now also
reported in the job console
This should help into getting a better understanding  on failures here.
=> Adding exception message on sendHTTPCall failure

README_PipelineConfiguration.md
It took me a while to figure out that updateBuildStatus() should be called. I see that it isused in one of the examples. But it is not included in the list of functions to call on the handle object. So I added it there
=> Update README adding updateBuildStatus()

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/pipeline/RemoteBuildPipelineStep.java
Looks like agent used only if `loadParamsFromFile` attribute defined, but now we always need hold agent for remote job.
=> Allow use `triggerRemoteJob` step with `agent none`

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/parameters2/FileParameters.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/parameters2/JobParameters.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/parameters2/MapParameter.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/parameters2/MapParameters.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/parameters2/StringParameters.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/pipeline/RemoteBuildPipelineStep.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/utils/HttpHelper.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/utils/TokenMacroUtils.java, src/main/resources/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration/config.jelly, src/main/resources/org/jenkinsci/plugins/ParameterizedRemoteTrigger/parameters2/FileParameters/config.jelly, src/main/resources/org/jenkinsci/plugins/ParameterizedRemoteTrigger/parameters2/MapParameter/config.jelly, src/main/resources/org/jenkinsci/plugins/ParameterizedRemoteTrigger/parameters2/MapParameters/config.jelly, src/main/resources/org/jenkinsci/plugins/ParameterizedRemoteTrigger/parameters2/StringParameters/config.jelly, src/test/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfigurationTest.java
This PR is an attempt to fix the current bugs with remote job parameters. It is linked to the JIRA issues [JENKINS-68737](https://issues.jenkins.io/browse/JENKINS-68737) and [JENKINS-58818](https://issues.jenkins.io/browse/JENKINS-58818).
Currently, the parameters are read from a single string and the following example:
```
MULTI_LINE=line1
line2
line3
```
actually creates the parameters `MULTI_LINE: 'line1'`, `line2: ''` & `line3: ''` which shows three parsing issues.
The splitting of the name/value is broken and cuts the `=` characters from the value (see [the JIRA issue](https://issues.jenkins.io/browse/JENKINS-58818))
The multi-line parameter's value is cut just after the first line.
The lines 2+ of the multi-line parameter are seen as variable names.
The issue can be fixed by having …
=> Improve parameters handling

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java
This PR fixes an issue, when enhancedLogging is set and remote log is trimmed. It adds a last poll for logs after the remote build finished.
=> fetch remaining log after remote job finishes

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/BasicBuildContext.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/BuildContext.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/ConnectionResponse.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteJenkinsServer.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/parameters2/FileParameters.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/parameters2/MapParameter.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/parameters2/MapParameters.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/parameters2/StringParameters.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/pipeline/Handle.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/pipeline/RemoteBuildPipelineStep.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/remoteJob/QueueItem.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/remoteJob/QueueItemData.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/remoteJob/RemoteBuildInfo.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/remoteJob/RemoteBuildInfoExporterAction.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/utils/Base64Utils.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/utils/HttpHelper.java
Annotations for Nonnull, CheckForNull, and several others were proposed for Java as part of dormant Java specification request JSR-305. The proposal never became a part of standard Java.
Jenkins plugins should switch from using JSR-305 annotations to use Spotbugs annotations that provide the same semantics.
The [mailing list discussion](https://groups.google.com/g/jenkinsci-dev/c/uE1wwtVi1W0/m/gLxdEJmlBQAJ) from James Nord describes the affected annotations and why they should be replaced with annotations that are actively maintained.
The ["Improve a plugin" tutorial](https://www.jenkins.io/doc/developer/tutorial-improve/replace-jsr-305-annotations/) provides instructions to perform this change.
An [OpenRewrite recipe](https://docs.openrewrite.org/recipes/jenkins/javaxannotationstospotbugs …
=> Replace JSR-305 annotations with spotbugs annotations

src/test/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/remoteJob/QueueItemTest.java
The goal was to adapt the changes of Jetty 12 EE 8 for `parameterized-remote-trigger-plugin` see https://issues.jenkins.io/browse/JENKINS-73142.
Post adaption of `Jetty12EE8`, `org.jenkinsci.plugins.ParameterizedRemoteTrigger.remoteJob.QueueItemTest` was failing at compile time.
In Jetty10, `org.eclipse.jetty.server.Response` inherits the http status codes (SC_Ok etc) from `javax.servlet.http.HttpServletResponse`  whereas in Jetty12 its not.
Used the status code 200 from `java.net.HttpURLConnection.HTTP_OK` rather than jetty. 
Tested locally & build passed.
=> [JENKINS-73142] Adapt Parameterized Remote Trigger for Jetty 12 (EE 8)

Jenkinsfile
Remove the jdk8 reference, since the plugin no longer supports JDK 8.
Provide link to Pipeline library documentation for details.
None.  Rely on ci.jenkins.io to confirm it works as expected.
=> Fix Jenkinsfile comments

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/auth2/BearerTokenAuth.java
Correct the bearer token header passed in the Parameterized Remote Trigger plugin.
The header when using bearer token authorization is incorrect because it contained an unnecessary colon `:`.
See issue https://issues.jenkins.io/browse/JENKINS-75957
=> JENKINS-75957: Correct bearer token header

src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteJenkinsServer.java, src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/utils/FormValidationUtils.java
As noted in #97, URLs ending in `/` do not seem to be supported. Documentation screenshots consistently show URLs without, so just treat that as required. I had a hard time following all the places where URLs are constructed, so adjusting all of them to tolerate URLs with or without a trailing slash seemed tricky.
=> Warn about URLs ending with slash
